# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y_4wC1SAYKSXiiDRC6-la9pqAR8CQ_Yr

# **Let's create new Telegram Bot**
"""

!pip install pytelegrambotapi

import telebot
from telebot import types

#@title Вставьте токен бота сюда и нажмите слева запуск
your_bot = "6930863171:AAEdMbICaqUz6XfHN1PriDcy_2ooTRjdFnU" #@param {type:"string"}
print('Ваш готов к запуску, проверьте в tg!\n(Правда нужно сначала научить его общаться)')

"""Now we are creating the new Bot in telegram from BotFather. There we can the get token of the Bot.

"""

# создадию переменные = сообщения, который мой бот будет отправлять

text7 = 'Я не понимаю тебя :( )'

from google.colab import files

# загружаю гиф на гугл коллаб
uploaded = files.upload()

import random # импоритируем библиотеку для работы со случайностями :)

food= ['Оладушки', 'Бутерброды', 'Омлет', 'Каша']

# Обновите доступ через токен
bot = telebot.TeleBot(your_bot)

@bot.message_handler(commands=["start"])
def start(message):

  # что произошло с командой старт: мы научим ее отправлять клавиатуру

  markup=types.ReplyKeyboardMarkup(resize_keyboard=True) # опишем клавиатуру
  item1=types.KeyboardButton("Идеи обеда?")
  item2=types.KeyboardButton("Что делать если я на диете?")
  item3=types.KeyboardButton("Идеи ужина?")
  item4=types.KeyboardButton("Идеи завтрака?")
  markup.row(item1) # кнопки
  markup.row(item3, item4) # расположение кнопок
  markup.row(item2)
  bot.send_message(message.chat.id, 'Добрый день! Это пробный бот занятия. Давайте посмотрим, как это работает :)', reply_markup=markup)
  # в конец команды старт приписали вывод клавиатуры, кусочек: , reply_markup=markup

@bot.message_handler(content_types=["text"])
def handle_text(message):
  if message.text.strip() == 'Что делать если я на диете?':
    # научим бот отправлять гифку
    img = open('kitty-eat-kitty-eating.mp4', 'rb')
    bot.send_animation(message.chat.id, img)
    # см. как отправить картинку, видео, аудио, стикер и многое другое: https://core.telegram.org/bots/api#animation
    answer1 = 'Не нужно переживать! Вот рецепт диетических пирожков:https://povar.ru/recipes/pirojki_v_duhovke-9955.html '
    answer2 = 'Есть и другой рецепт : https://1000.menu/cooking/18419-sladkie-pirojki-iz-drojjevogo-testa  '
    bot.send_message(message.chat.id, answer1)
    bot.send_message(message.chat.id, answer2)

  elif message.text.strip() == 'Идеи ужина?':
    answer1 = 'Мой любимый рецепт пирога тут: https://www.edimdoma.ru/retsepty/76255-italyanskiy-derevenskiy-yablochnyy-pirog '
    bot.send_message(message.chat.id, answer1)

  elif message.text.strip() == 'Идеи завтрака?':
    bot.send_message(message.chat.id, random.choice(food), parse_mode="Markdown")

  elif message.text.strip() == 'Идеи обеда?':
    answer1 = 'Отправляем!\n https://povar.ru/recipes/pirojki_v_duhovke-9955.html'
    bot.send_message(message.chat.id, answer1)

  else:
    bot.send_message(message.chat.id, text7)

# Запускаем бота
bot.polling(none_stop=True, interval=0)